CREATE DATABASE EntreEntrelinhasWeb;

USE EntreEntrelinhasWeb;

CREATE TABLE usuarios (
USU_INT_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
USU_STR_NOMEUSUARIO VARCHAR(50) NOT NULL,
USU_STR_NOMECOMPLETO VARCHAR(100) NOT NULL,
USU_STR_EMAIL VARCHAR(100) NOT NULL UNIQUE,
USU_STR_SENHA VARCHAR(255) NOT NULL,
USU_DTA_CADASTRO DATETIME NOT NULL
)

CREATE TABLE projetos (
PRO_INT_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
PRO_STR_NOME VARCHAR(100) NOT NULL,
PRO_STR_DESCRICAO VARCHAR(500),
PRO_STR_TIPO VARCHAR(50),
PRO_DTA_CRIACAO DATETIME NOT NULL,
PRO_DTA_ULTIMAEDICAO DATETIME,
USU_INT_ID INT NOT NULL,

FOREIGN KEY (USU_INT_ID)
REFERENCES usuarios(USU_INT_ID)

)

CREATE TABLE capitulos (
CAP_INT_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
CAP_INT_NUMERO INT NOT NULL,
CAP_STR_TITULO VARCHAR(100) NOT NULL,
CAP_STR_TEXTO VARCHAR(MAX),
CAP_INT_QUANTPALAVRAS INT,
CAP_DTA_ULTIMAEDICAO DATETIME,
PRO_INT_ID INT NOT NULL,

FOREIGN KEY (PRO_INT_ID)
REFERENCES projetos(PRO_INT_ID)

)

CREATE TABLE personagens (
PER_INT_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
PER_STR_NOME VARCHAR(100) NOT NULL,
PER_STR_IDADE VARCHAR(100),
PER_STR_APARENCIA VARCHAR(MAX),
PER_STR_PERSONALIDADE VARCHAR(MAX),
PER_STR_HISTORIA VARCHAR(MAX),
PRO_INT_ID INT NOT NULL,

FOREIGN KEY (PRO_INT_ID)
REFERENCES projetos(PRO_INT_ID)


)

CREATE TABLE locais (
LOC_INT_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
LOC_STR_NOME VARCHAR(100) NOT NULL,
LOC_STR_TIPO VARCHAR(50),
LOC_STR_ATMOSFERA VARCHAR(MAX),
LOC_STR_ACONTECIMENTOS VARCHAR(MAX),
LOC_STR_DESCRICAO VARCHAR(MAX),
PRO_INT_ID INT NOT NULL,

FOREIGN KEY (PRO_INT_ID)
REFERENCES projetos(PRO_INT_ID)
)

CREATE TABLE conflitos (
CON_INT_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
CON_STR_NOME VARCHAR(100) NOT NULL,
CON_STR_ESCALA VARCHAR(50),
CON_STR_LADOS VARCHAR(MAX),
CON_STR_MOTIVACAO VARCHAR (MAX),
CON_STR_DESCRICAO VARCHAR(MAX),
PRO_INT_ID INT NOT NULL,

FOREIGN KEY (PRO_INT_ID)
REFERENCES projetos(PRO_INT_ID)
)

CREATE TABLE notas(
NOT_INT_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
NOT_STR_TITULO VARCHAR(100) NOT NULL,
NOT_STR_CONTEUDO VARCHAR(MAX),
NOT_DTA_ULTIMAEDICAO DATETIME,
PRO_INT_ID INT NOT NULL,

FOREIGN KEY (PRO_INT_ID)
REFERENCES projetos(PRO_INT_ID)
)

CREATE TABLE eventosCronologia (
EVE_INT_ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
EVE_INT_ORDEM INT NOT NULL,
EVE_STR_TITULO VARCHAR(100) NOT NULL,
EVE_STR_DESCRICAO VARCHAR(MAX),
PRO_INT_ID INT NOT NULL,

FOREIGN KEY (PRO_INT_ID)
REFERENCES projetos(PRO_INT_ID)
)